services:
  # Production
  - type: web
    name: ng-docker
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: ./bin/render-build.sh
    startCommand: ng deploy
    # envVars:
    #   - fromGroup: ng-docker
