services:
  # Production
  - type: web
    name: ng-docker
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: ./bin/render-build.sh
    startCommand: NODE_OPTIONS="--max-old-space-size=4096" ng serve --prod --output-hashing none
    # envVars:
    #   - fromGroup: ng-docker
